#pragma once

#include "Arduino.h"
#include "StreamingOperator.hpp"
#include "Homie/Datatypes/Interface.hpp"
#include "HomieRange.hpp"

class HomieNode;

namespace HomieInternals {
class SendingPromise {
  friend ::HomieNode;

 public:
  SendingPromise();
  SendingPromise& setQos(uint8_t qos);
  SendingPromise& setRetained(bool retained);
  // Fork extension: controls only the mirrored /set publish generated by
  // overwriteSetter(true). The main property publish still uses setRetained().
  SendingPromise& setSetRetained(bool retained);
  SendingPromise& overwriteSetter(bool overwrite);
  SendingPromise& setRange(const HomieRange& range);
  SendingPromise& setRange(uint16_t rangeIndex);
  uint16_t send(const String& value);

 private:
  // One SendingPromise instance is reused globally; reset prevents a previous
  // send's qos/retained/range choices from leaking into the next property send.
  SendingPromise& reset();
  SendingPromise& setNode(const HomieNode& node);
  SendingPromise& setProperty(const String& property);
  const HomieNode* getNode() const;
  const String* getProperty() const;
  uint8_t getQos() const;
  HomieRange getRange() const;
  bool isRetained() const;
  bool doesOverwriteSetter() const;

  const HomieNode* _node;
  const String* _property;
  uint8_t _qos;
  bool _retained;
  bool _setRetained;
  bool _overwriteSetter;
  HomieRange _range;
};
}  // namespace HomieInternals
